@Test public void testDefaultPasswordAutogeneratedIfEmpty(){
  this.binder.bind(new MutablePropertyValues(Collections.singletonMap("security.user.password","")));
  assertFalse(this.binder.getBindingResult().hasErrors());
  assertTrue(this.security.getUser().isDefaultPassword());
}
