@Test public void testConnectionRedistributionOnTotalMaxLimit() throws Exception {
  HttpConnectionFactory connFactory=Mockito.mock(HttpConnectionFactory.class);
  HttpConnection conn1=Mockito.mock(HttpConnection.class);
  HttpConnection conn2=Mockito.mock(HttpConnection.class);
  HttpConnection conn3=Mockito.mock(HttpConnection.class);
  Mockito.when(connFactory.create(Mockito.eq("somehost"))).thenReturn(conn1,conn2,conn3);
  HttpConnection conn4=Mockito.mock(HttpConnection.class);
  HttpConnection conn5=Mockito.mock(HttpConnection.class);
  Mockito.when(connFactory.create(Mockito.eq("otherhost"))).thenReturn(conn4,conn5);
  LocalConnPool pool=new LocalConnPool(connFactory,2,10);
  pool.setMaxPerRoute("somehost",2);
  pool.setMaxPerRoute("otherhost",2);
  pool.setMaxTotal(2);
  Future<LocalPoolEntry> future1=pool.lease("somehost",null);
  GetPoolEntryThread t1=new GetPoolEntryThread(future1);
  t1.start();
  Future<LocalPoolEntry> future2=pool.lease("somehost",null);
  GetPoolEntryThread t2=new GetPoolEntryThread(future2);
  t2.start();
  t1.join(GRACE_PERIOD);
  Assert.assertTrue(future1.isDone());
  LocalPoolEntry entry1=t1.getEntry();
  Assert.assertNotNull(entry1);
  t2.join(GRACE_PERIOD);
  Assert.assertTrue(future2.isDone());
  LocalPoolEntry entry2=t2.getEntry();
  Assert.assertNotNull(entry2);
  Future<LocalPoolEntry> future3=pool.lease("otherhost",null);
  GetPoolEntryThread t3=new GetPoolEntryThread(future3);
  t3.start();
  Future<LocalPoolEntry> future4=pool.lease("otherhost",null);
  GetPoolEntryThread t4=new GetPoolEntryThread(future4);
  t4.start();
  Assert.assertFalse(t3.isDone());
  Assert.assertFalse(t4.isDone());
  Mockito.verify(connFactory,Mockito.times(2)).create(Mockito.eq("somehost"));
  Mockito.verify(connFactory,Mockito.never()).create(Mockito.eq("otherhost"));
  PoolStats totals=pool.getTotalStats();
  Assert.assertEquals(0,totals.getAvailable());
  Assert.assertEquals(2,totals.getLeased());
  pool.release(entry1,true);
  pool.release(entry2,true);
  t3.join(GRACE_PERIOD);
  Assert.assertTrue(future3.isDone());
  LocalPoolEntry entry3=t3.getEntry();
  Assert.assertNotNull(entry3);
  t4.join(GRACE_PERIOD);
  Assert.assertTrue(future4.isDone());
  LocalPoolEntry entry4=t4.getEntry();
  Assert.assertNotNull(entry4);
  Mockito.verify(connFactory,Mockito.times(2)).create(Mockito.eq("somehost"));
  Mockito.verify(connFactory,Mockito.times(2)).create(Mockito.eq("otherhost"));
  totals=pool.getTotalStats();
  Assert.assertEquals(0,totals.getAvailable());
  Assert.assertEquals(2,totals.getLeased());
  Future<LocalPoolEntry> future5=pool.lease("somehost",null);
  GetPoolEntryThread t5=new GetPoolEntryThread(future5);
  t5.start();
  Future<LocalPoolEntry> future6=pool.lease("otherhost",null);
  GetPoolEntryThread t6=new GetPoolEntryThread(future6);
  t6.start();
  pool.release(entry3,true);
  pool.release(entry4,true);
  t5.join(GRACE_PERIOD);
  Assert.assertTrue(future5.isDone());
  LocalPoolEntry entry5=t5.getEntry();
  Assert.assertNotNull(entry5);
  t6.join(GRACE_PERIOD);
  Assert.assertTrue(future6.isDone());
  LocalPoolEntry entry6=t6.getEntry();
  Assert.assertNotNull(entry6);
  Mockito.verify(connFactory,Mockito.times(3)).create(Mockito.eq("somehost"));
  Mockito.verify(connFactory,Mockito.times(2)).create(Mockito.eq("otherhost"));
  totals=pool.getTotalStats();
  Assert.assertEquals(0,totals.getAvailable());
  Assert.assertEquals(2,totals.getLeased());
  pool.release(entry5,true);
  pool.release(entry6,true);
  totals=pool.getTotalStats();
  Assert.assertEquals(2,totals.getAvailable());
  Assert.assertEquals(0,totals.getLeased());
}
