@Test public void threeNodes() throws Exception {
  MemoryDocumentStore ds=new MemoryDocumentStore();
  MemoryBlobStore bs=new MemoryBlobStore();
  DocumentMK.Builder builder;
  builder=new DocumentMK.Builder();
  builder.setDocumentStore(ds).setBlobStore(bs).setAsyncDelay(0);
  DocumentMK mk1=builder.setClusterId(1).open();
  builder=new DocumentMK.Builder();
  builder.setDocumentStore(ds).setBlobStore(bs).setAsyncDelay(0);
  DocumentMK mk2=builder.setClusterId(2).open();
  builder=new DocumentMK.Builder();
  builder.setDocumentStore(ds).setBlobStore(bs).setAsyncDelay(0);
  DocumentMK mk3=builder.setClusterId(3).open();
  mk1.commit("/","+\"test\":{}",null,null);
  mk2.commit("/","+\"a\":{}",null,null);
  mk3.commit("/","+\"b\":{}",null,null);
  mk2.backgroundWrite();
  mk2.backgroundRead();
  mk3.backgroundWrite();
  mk3.backgroundRead();
  mk1.backgroundWrite();
  mk1.backgroundRead();
  mk2.backgroundWrite();
  mk2.backgroundRead();
  mk3.backgroundWrite();
  mk3.backgroundRead();
  mk2.commit("/","^\"test/x\":1",null,null);
  String n3=mk3.getNodes("/test",mk3.getHeadRevision(),0,0,10,null);
  assertEquals("{\":childNodeCount\":0}",n3);
  mk3.commit("/","^\"test/y\":2",null,null);
  mk3.backgroundWrite();
  mk3.backgroundRead();
  mk1.backgroundWrite();
  mk1.backgroundRead();
  String r1=mk1.getHeadRevision();
  String n1=mk1.getNodes("/test",r1,0,0,10,null);
  assertEquals("{\"y\":2,\":childNodeCount\":0}",n1);
  mk2.backgroundWrite();
  mk2.backgroundRead();
  mk1.backgroundWrite();
  mk1.backgroundRead();
  String r1b=mk1.getHeadRevision();
  String n1b=mk1.getNodes("/test",r1b,0,0,10,null);
  JSONParser parser=new JSONParser();
  JSONObject obj=(JSONObject)parser.parse(n1b);
  assertEquals(1L,obj.get("x"));
  assertEquals(2L,obj.get("y"));
  assertEquals(0L,obj.get(":childNodeCount"));
  mk1.dispose();
  mk2.dispose();
  mk3.dispose();
}
