@Test public void setNext(){
  NodeBuilder n=EmptyNodeState.EMPTY_NODE.builder();
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"foobar");
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals(ImmutableList.of("foobar","","",""),n.getProperty(NEXT).getValue(Type.STRINGS));
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,(String[])null);
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals("If I set a value to null, nothing should change",ImmutableList.of("foobar","","",""),n.getProperty(NEXT).getValue(Type.STRINGS));
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"");
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals(ImmutableList.of("","","",""),n.getProperty(NEXT).getValue(Type.STRINGS));
  n=EmptyNodeState.EMPTY_NODE.builder();
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"a","b");
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals(ImmutableList.of("a","b","",""),n.getProperty(NEXT).getValue(Type.STRINGS));
  n=EmptyNodeState.EMPTY_NODE.builder();
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"a","b","c");
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals(ImmutableList.of("a","b","c",""),n.getProperty(NEXT).getValue(Type.STRINGS));
  n=EmptyNodeState.EMPTY_NODE.builder();
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"a","b","c","d");
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals(ImmutableList.of("a","b","c","d"),n.getProperty(NEXT).getValue(Type.STRINGS));
  n=EmptyNodeState.EMPTY_NODE.builder();
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"a","b","c","d","e","f");
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals("even if we provide more than 4 nexts we expect it to take only the first 4s",ImmutableList.of("a","b","c","d"),n.getProperty(NEXT).getValue(Type.STRINGS));
  n=EmptyNodeState.EMPTY_NODE.builder();
  n.setProperty(NEXT,ImmutableList.of("a","b","c","d"),Type.STRINGS);
  OrderedContentMirrorStoreStrategy.setPropertyNext(n,"a",3);
  assertNotNull(n);
  assertNotNull(":next cannot be null",n.getProperty(NEXT));
  assertEquals(ImmutableList.of("a","b","c","a"),n.getProperty(NEXT).getValue(Type.STRINGS));
}
