@Test public void excerpt() throws Exception {
  Session session=getAdminSession();
  QueryManager qm=session.getWorkspace().getQueryManager();
  Node testRootNode=session.getRootNode().addNode("testroot");
  Node n1=testRootNode.addNode("node1");
  n1.setProperty("text","hello world");
  n1.setProperty("desc","description");
  Node n2=testRootNode.addNode("node2");
  n2.setProperty("text","Hello World");
  n2.setProperty("desc","Description");
  session.save();
  Query q;
  RowIterator it;
  Row row;
  String s;
  String xpath="//*[jcr:contains(., 'hello')]/rep:excerpt(.) order by @jcr:path";
  q=qm.createQuery(xpath,"xpath");
  it=q.execute().getRows();
  row=it.nextRow();
  String path=row.getPath();
  s=row.getValue("rep:excerpt(.)").getString();
  assertTrue(path + ":" + s+ " (1)",s.indexOf("<strong>hello</strong> world") >= 0);
  assertTrue(path + ":" + s+ " (2)",s.indexOf("description") >= 0);
  row=it.nextRow();
  path=row.getPath();
  s=row.getValue("rep:excerpt(.)").getString();
  assertTrue(path + ":" + s+ " (3)",s.indexOf("Hello World") >= 0);
  assertTrue(path + ":" + s+ " (4)",s.indexOf("Description") >= 0);
  xpath="//*[jcr:contains(., 'hello')]/rep:excerpt(.) order by @jcr:path";
  q=qm.createQuery(xpath,"xpath");
  it=q.execute().getRows();
  row=it.nextRow();
  path=row.getPath();
  s=row.getValue("rep:excerpt(text)").getString();
  assertTrue(path + ":" + s+ " (5)",s.indexOf("<strong>hello</strong> world") >= 0);
  assertTrue(path + ":" + s+ " (6)",s.indexOf("description") < 0);
  row=it.nextRow();
  path=row.getPath();
  s=row.getValue("rep:excerpt(text)").getString();
  assertTrue(path + ":" + s+ " (7)",s.indexOf("Hello World") >= 0);
  assertTrue(path + ":" + s+ " (8)",s.indexOf("Description") < 0);
}
