@Test public void testJcrToOakKeepIndex(){
  assertEquals("/",npMapper.getOakPathKeepIndex("/"));
  assertEquals("foo",npMapper.getOakPathKeepIndex("{}foo"));
  assertEquals("/oak-foo:bar",npMapper.getOakPathKeepIndex("/foo:bar"));
  assertEquals("/oak-foo:bar/oak-quu:qux",npMapper.getOakPathKeepIndex("/foo:bar/quu:qux"));
  assertEquals("oak-foo:bar",npMapper.getOakPathKeepIndex("foo:bar"));
  assertEquals("oak-nt:unstructured",npMapper.getOakPathKeepIndex("{http://www.jcp.org/jcr/nt/1.0}unstructured"));
  assertEquals("foobar/oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content"));
  assertEquals("foobar",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content/.."));
  assertEquals("",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content/../.."));
  assertEquals("..",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content/../../.."));
  assertEquals("../..",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content/../../../.."));
  assertEquals("oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/../{http://www.jcp.org/jcr/1.0}content"));
  assertEquals("../oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/../../{http://www.jcp.org/jcr/1.0}content"));
  assertEquals("..",npMapper.getOakPathKeepIndex(".."));
  assertEquals("",npMapper.getOakPathKeepIndex("."));
  assertEquals("foobar/oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content/."));
  assertEquals("foobar/oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/{http://www.jcp.org/jcr/1.0}content/./."));
  assertEquals("foobar/oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/./{http://www.jcp.org/jcr/1.0}content"));
  assertEquals("oak-jcr:content",npMapper.getOakPathKeepIndex("foobar/./../{http://www.jcp.org/jcr/1.0}content"));
  assertEquals("/a/b[1]/c[1]",npMapper.getOakPathKeepIndex("/a/b[1]/c[01]"));
}
