@Test public void testFurniture(){
  Chair chair=new Chair();
  chair.setId(1);
  chair.setMaterial("wood");
  chair.setColor("brown");
  chair.setArms(true);
  chair.setRecliner(false);
  entityMgr.persist(chair);
  Couch couch=new Couch();
  couch.setId(2);
  couch.setMaterial("wood");
  couch.setColor("brown");
  couch.setFoldOutBed(false);
  couch.setNumCushions(3);
  entityMgr.persist(couch);
  Table table=new Table();
  table.setId(3);
  table.setMaterial("formica");
  table.setColor("blue");
  table.setExtendable(true);
  table.setShape("circle");
  entityMgr.persist(table);
  Desk desk=new Desk();
  desk.setId(4);
  desk.setMaterial("pressBoard");
  desk.setColor("black");
  desk.setExtendable(false);
  desk.setShape("rectangle");
  desk.setNumDrawers(2);
  entityMgr.persist(desk);
  Furniture f1=entityMgr.find(Furniture.class,1);
  Furniture f2=entityMgr.find(Furniture.class,2);
  Furniture f3=entityMgr.find(Furniture.class,3);
  Furniture f4=entityMgr.find(Furniture.class,4);
  assertEquals(Chair.class,f1.getClass());
  assertEquals(Couch.class,f2.getClass());
  assertEquals(Table.class,f3.getClass());
  assertEquals(Desk.class,f4.getClass());
}
