@Deployment(resources={"org/activiti/standalone/history/FullHistoryTest.testHistoricProcessInstanceVariableValueEquals.bpmn20.xml"}) public void testHistoricProcessInstanceVariableValueNotEquals() throws Exception {
  Map<String,Object> variables=new HashMap<String,Object>();
  variables.put("longVar",12345L);
  variables.put("shortVar",(short)123);
  variables.put("integerVar",1234);
  variables.put("stringVar","stringValue");
  variables.put("booleanVar",true);
  Date date=Calendar.getInstance().getTime();
  Calendar otherCal=Calendar.getInstance();
  otherCal.add(Calendar.DAY_OF_MONTH,1);
  Date otherDate=otherCal.getTime();
  variables.put("dateVar",date);
  variables.put("nullVar",null);
  ProcessInstance processInstance=runtimeService.startProcessInstanceByKey("HistoricProcessInstanceTest",variables);
  assertEquals(7,historyService.createHistoricDetailQuery().variableUpdates().processInstanceId(processInstance.getId()).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("longVar",12345L).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("shortVar",(short)123).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("integerVar",1234).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("stringVar","stringValue").count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("booleanVar",true).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("dateVar",date).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("nullVar",null).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("nullVar",null).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("longVar",67890L).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("shortVar",(short)456).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("integerVar",5678).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("stringVar","updatedStringValue").count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("booleanVar",false).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("dateVar",otherDate).count());
  variables.put("longVar",67890L);
  variables.put("shortVar",(short)456);
  variables.put("integerVar",5678);
  variables.put("stringVar","updatedStringValue");
  variables.put("booleanVar",false);
  variables.put("dateVar",otherDate);
  variables.put("nullVar",null);
  runtimeService.setVariables(processInstance.getId(),variables);
  assertEquals(14,historyService.createHistoricDetailQuery().variableUpdates().processInstanceId(processInstance.getId()).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("longVar",12345L).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("shortVar",(short)123).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("integerVar",1234).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("stringVar","stringValue").count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("booleanVar",true).count());
  assertEquals(1,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("dateVar",date).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("longVar",67890L).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("shortVar",(short)456).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("integerVar",5678).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("stringVar","updatedStringValue").count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("booleanVar",false).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("dateVar",otherDate).count());
  assertEquals(0,historyService.createHistoricProcessInstanceQuery().variableValueNotEquals("nullVar",null).count());
}
