@Deployment(resources={"org/activiti/engine/test/api/oneTaskProcess.bpmn20.xml"}) public void testQueryLongVariable(){
  Map<String,Object> vars=new HashMap<String,Object>();
  vars.put("longVar",12345L);
  ProcessInstance processInstance1=runtimeService.startProcessInstanceByKey("oneTaskProcess",vars);
  vars=new HashMap<String,Object>();
  vars.put("longVar",12345L);
  vars.put("longVar2",67890L);
  ProcessInstance processInstance2=runtimeService.startProcessInstanceByKey("oneTaskProcess",vars);
  vars=new HashMap<String,Object>();
  vars.put("longVar",55555L);
  ProcessInstance processInstance3=runtimeService.startProcessInstanceByKey("oneTaskProcess",vars);
  ExecutionQuery query=runtimeService.createExecutionQuery().variableValueEquals("longVar",12345L);
  List<Execution> executions=query.list();
  assertNotNull(executions);
  assertEquals(2,executions.size());
  query=runtimeService.createExecutionQuery().variableValueEquals("longVar",12345L).variableValueEquals("longVar2",67890L);
  Execution execution=query.singleResult();
  assertNotNull(execution);
  assertEquals(processInstance2.getId(),execution.getId());
  execution=runtimeService.createExecutionQuery().variableValueEquals("longVar",999L).singleResult();
  assertNull(execution);
  execution=runtimeService.createExecutionQuery().variableValueNotEquals("longVar",12345L).singleResult();
  assertNotNull(execution);
  assertEquals(processInstance3.getId(),execution.getId());
  execution=runtimeService.createExecutionQuery().variableValueGreaterThan("longVar",44444L).singleResult();
  assertNotNull(execution);
  assertEquals(processInstance3.getId(),execution.getId());
  assertEquals(0,runtimeService.createExecutionQuery().variableValueGreaterThan("longVar",55555L).count());
  assertEquals(3,runtimeService.createExecutionQuery().variableValueGreaterThan("longVar",1L).count());
  execution=runtimeService.createExecutionQuery().variableValueGreaterThanOrEqual("longVar",44444L).singleResult();
  assertNotNull(execution);
  assertEquals(processInstance3.getId(),execution.getId());
  execution=runtimeService.createExecutionQuery().variableValueGreaterThanOrEqual("longVar",55555L).singleResult();
  assertNotNull(execution);
  assertEquals(processInstance3.getId(),execution.getId());
  assertEquals(3,runtimeService.createExecutionQuery().variableValueGreaterThanOrEqual("longVar",1L).count());
  executions=runtimeService.createExecutionQuery().variableValueLessThan("longVar",55555L).list();
  assertEquals(2,executions.size());
  List<String> expectedIds=Arrays.asList(processInstance1.getId(),processInstance2.getId());
  List<String> ids=new ArrayList<String>(Arrays.asList(executions.get(0).getId(),executions.get(1).getId()));
  ids.removeAll(expectedIds);
  assertTrue(ids.isEmpty());
  assertEquals(0,runtimeService.createExecutionQuery().variableValueLessThan("longVar",12345L).count());
  assertEquals(3,runtimeService.createExecutionQuery().variableValueLessThan("longVar",66666L).count());
  executions=runtimeService.createExecutionQuery().variableValueLessThanOrEqual("longVar",55555L).list();
  assertEquals(3,executions.size());
  assertEquals(0,runtimeService.createExecutionQuery().variableValueLessThanOrEqual("longVar",12344L).count());
  execution=runtimeService.createExecutionQuery().variableValueEquals(55555L).singleResult();
  assertNotNull(execution);
  assertEquals(processInstance3.getId(),execution.getId());
  executions=runtimeService.createExecutionQuery().variableValueEquals(12345L).list();
  assertEquals(2,executions.size());
  expectedIds=Arrays.asList(processInstance1.getId(),processInstance2.getId());
  ids=new ArrayList<String>(Arrays.asList(executions.get(0).getId(),executions.get(1).getId()));
  ids.removeAll(expectedIds);
  assertTrue(ids.isEmpty());
  execution=runtimeService.createExecutionQuery().variableValueEquals(99999L).singleResult();
  assertNull(execution);
  runtimeService.deleteProcessInstance(processInstance1.getId(),"test");
  runtimeService.deleteProcessInstance(processInstance2.getId(),"test");
  runtimeService.deleteProcessInstance(processInstance3.getId(),"test");
}
