@Deployment public void testCatchErrorInConcurrentEmbeddedSubprocessesThrownByScriptTask(){
  assertErrorCaughtInConcurrentEmbeddedSubprocesses("catchErrorInConcurrentEmbeddedSubprocessesThrownByScriptTask");
}
