@Test public void addComplexResourceAdapterWithElytronAuthCtxt() throws Exception {
  complexResourceAdapterAddTest(ConnectionSecurityType.ELYTRON_AUTHENTICATION_CONTEXT,ConnectionSecurityType.ELYTRON_AUTHENTICATION_CONTEXT);
}
