@Test public void testNameImplies(){
  assertEquals(new JndiPermission("<<ALL BINDINGS>>","*"),new JndiPermission("-","*"));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("-","*")));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("","*")));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("foo","*")));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("/foo","*")));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("foo/","*")));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("foo/bar/baz/zap","*")));
  assertTrue(new JndiPermission("-","*").implies(new JndiPermission("java:foo","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("/-","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("/","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("//","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("////","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("/foo","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("/foo","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("/foo/","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("/foo/bar/baz/zap","*")));
  assertTrue(new JndiPermission("/-","*").implies(new JndiPermission("java:/foo","*")));
  assertTrue(new JndiPermission("foo/-","*").implies(new JndiPermission("foo/-","*")));
  assertTrue(new JndiPermission("foo/-","*").implies(new JndiPermission("foo/foo","*")));
  assertTrue(new JndiPermission("foo/-","*").implies(new JndiPermission("foo/foo","*")));
  assertTrue(new JndiPermission("foo/-","*").implies(new JndiPermission("foo/foo/","*")));
  assertTrue(new JndiPermission("foo/-","*").implies(new JndiPermission("foo/foo/bar/baz/zap","*")));
  assertTrue(new JndiPermission("foo/-","*").implies(new JndiPermission("java:foo/foo","*")));
  assertTrue(new JndiPermission("*","*").implies(new JndiPermission("","*")));
  assertTrue(new JndiPermission("*","*").implies(new JndiPermission("foo","*")));
  assertFalse(new JndiPermission("*","*").implies(new JndiPermission("foo/bar","*")));
  assertFalse(new JndiPermission("*","*").implies(new JndiPermission("foo/","*")));
  assertFalse(new JndiPermission("*","*").implies(new JndiPermission("/foo","*")));
  assertTrue(new JndiPermission("*/*","*").implies(new JndiPermission("/foo","*")));
  assertTrue(new JndiPermission("/*","*").implies(new JndiPermission("/foo","*")));
  assertTrue(new JndiPermission("*/foo","*").implies(new JndiPermission("/foo","*")));
  assertEquals(new JndiPermission("java:","*"),new JndiPermission("","*"));
  assertEquals(new JndiPermission("java:/","*"),new JndiPermission("/","*"));
  assertEquals(new JndiPermission("java:-","*"),new JndiPermission("-","*"));
  assertEquals(new JndiPermission("java:*","*"),new JndiPermission("*","*"));
}
