@Test public void should_query_with_default_params() throws Exception {
  long partitionKey=RandomUtils.nextLong();
  List<ClusteredEntityWithCounter> entities=manager.sliceQuery(ClusteredEntityWithCounter.class).partitionComponents(partitionKey).fromClusterings("name2").toClusterings("name4").get();
  assertThat(entities).isEmpty();
  insertValues(partitionKey,5);
  entities=manager.sliceQuery(ClusteredEntityWithCounter.class).partitionComponents(partitionKey).fromClusterings("name2").toClusterings("name4").get();
  assertThat(entities).hasSize(3);
  assertThat(entities.get(0).getCounter().get()).isEqualTo(2);
  assertThat(entities.get(0).getVersion().get()).isEqualTo(2);
  assertThat(entities.get(0).getId().getId()).isEqualTo(partitionKey);
  assertThat(entities.get(0).getId().getName()).isEqualTo("name2");
  assertThat(entities.get(1).getCounter().get()).isEqualTo(3);
  assertThat(entities.get(1).getVersion().get()).isEqualTo(3);
  assertThat(entities.get(1).getId().getId()).isEqualTo(partitionKey);
  assertThat(entities.get(1).getId().getName()).isEqualTo("name3");
  assertThat(entities.get(2).getCounter().get()).isEqualTo(4);
  assertThat(entities.get(2).getVersion().get()).isEqualTo(4);
  assertThat(entities.get(2).getId().getId()).isEqualTo(partitionKey);
  assertThat(entities.get(2).getId().getName()).isEqualTo("name4");
  entities=manager.sliceQuery(ClusteredEntityWithCounter.class).fromEmbeddedId(new ClusteredKey(partitionKey,"name2")).toEmbeddedId(new ClusteredKey(partitionKey,"name4")).get();
  assertThat(entities).hasSize(3);
  assertThat(entities.get(0).getCounter().get()).isEqualTo(2);
  assertThat(entities.get(0).getVersion().get()).isEqualTo(2);
  assertThat(entities.get(0).getId().getId()).isEqualTo(partitionKey);
  assertThat(entities.get(0).getId().getName()).isEqualTo("name2");
  assertThat(entities.get(1).getCounter().get()).isEqualTo(3);
  assertThat(entities.get(1).getVersion().get()).isEqualTo(3);
  assertThat(entities.get(1).getId().getId()).isEqualTo(partitionKey);
  assertThat(entities.get(1).getId().getName()).isEqualTo("name3");
  assertThat(entities.get(2).getCounter().get()).isEqualTo(4);
  assertThat(entities.get(2).getVersion().get()).isEqualTo(4);
  assertThat(entities.get(2).getId().getId()).isEqualTo(partitionKey);
  assertThat(entities.get(2).getId().getName()).isEqualTo("name4");
}
